exclude: ['out', 'submodules']
paginate_path: 'page:num'
markdown: kramdown
sass:
    sass_dir: .
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      meta_title: true
  -
    scope:
      path: 'r'
    values:
      layout: 'redirect'
      sitemap: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

asciidoctor:
  attributes:
    sectanchors: true
    sectlinks: true
    sectnumlevels: 6
    sectnums: true
    stem: ''
    toc-title: ''
    toc: macro
    toclevels: 6

# Data.
github: https://github.com/cirosantilli
twitter: https://twitter.com/cirosantilli
name: Ciro Santilli
toc: |
  1. a
  {:toc}
