paginate_path: 'page:num'
markdown: kramdown
sass:
    sass_dir: assets

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      meta_title: true
  -
    scope:
      path: 'r'
    values:
      layout: 'redirect'
      sitemap: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Data.
comments: false
files_path: files/
github: https://github.com/cirosantilli
twitter: https://twitter.com/cirosantilli
name: Ciro Santilli
navigation:
- text: Articles
  url: /articles
- text: Projects
  url: /projects
- text: Skills
  url: /skills
- text: Interests
  url: /interests
- text: Education
  url: /education
toc: |
  1. a
  {:toc}
