baseurl: /
permalink: /:title/
paginate_path: 'page:num'
markdown: kramdown
sass:
    sass_dir: assets

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      meta_title: true
      social_media: false
  -
    scope:
      path: 'r'
    values:
      layout: 'redirect'
      sitemap: false
  -
    scope:
      path: 'git-tutorial'
    values:
      social_media: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Data.
comments: true
email: ciro.santilli.contact@gmail.com
files_path: files/
github: https://github.com/cirosantilli
name: Ciro Santilli
navigation:
- text: Articles
  url: /articles
- text: Projects
  url: /projects
- text: CV
  url: /files/cv.pdf
- text: Skills
  url: /skills
- text: Interests
  url: /interests
- text: Education
  url: /education
toc: |
  1. a
  {:toc}
