#permalink:     date
baseurl: /
permalink: /:title
paginate_path: 'page:num'
markdown: kramdown
sass:
    sass_dir: assets

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default'
      meta_title: true
      social_media: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Data.
comments: true
email: ciro.santilli.contact@gmail.com
files_path: files/
github: https://github.com/cirosantilli
name: Ciro Santilli
toc: |
  1. a
  {:toc}
